version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: ls -la
          name: enter backend
      - run:
          command: npm install
          name: install deps
      - run: 
          command: npx tsc --jsx react-jsx
          name: transpile ts to js

  deploy:
      

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy